### ISSUE TITLE
ToDo for initial release

### ISSUE THREAD

**Issue by kelunik** [amphp/hpack#1]
- [x] Review public API.
 - [x] Make class `final`.
 - [ ] Create `README.md`.

**Comment by joelwurtz** [comment]
About public API, here is my 2 cents : 

 * It should not mention huffman in public methods (most people don't [want to] care about it)
 * There should be no init method (if required it should be private / lazy, i don't want to care about it, and if many libraries use it i don't know if it's already initialized or not)
 * IMO it should have only 2 methods (static or simple functions) : 

```php
[public static] function encodeHeaders(array $headers): string;

[public static] function decodeHeaders(string $binary): array;
```

But not sure on how works hpack precisely and if it's possible to have this api

**Comment by kelunik** [comment]
@joelwurtz You don't have to call `init()`, it's automatically called at the end of the file and lazy, because it's only executed when the file is required.

Two methods aren't possible, because the dictionary can grow (but I think currently does not).

**Comment by trowski** [comment]
I moved the `init()` call to be done immediately by the autoloader because it causes significant latency on the first HTTP/2 request, so I think it would be better to do at startup.

I'm not entirely clear on why there are public `huffmanEncode` and `huffmanDecode` methods. Those likely should just be private. The public API only really needs to consist of `encode`, `decode`, and `tableResize`. `encode` should be an instance method, since it should be using a dynamic table for encoding (not implemented yet, but making it an instance method will allow that at any time).

**Comment by kelunik** [comment]
Shouldn't it be `resizeTable()`?

I guess the rest should be private and the initialization maybe done via `(function () { static::init(); })->bindTo(null, HPack::class)();`

**Comment by bwoebi** [comment]
The huffmanEncode/huffmanDecode functions are specific if you want to roll your own HPack (e.g. with a dynamic table). You do not need them for header encoding and decoding. That's what `HPack::encode()` and `HPack::decode()` are for.

They are more like helper functions, which I decided to make public - if one needs them. Ultimately they are specified by the RFC, have well-defined ins and outs.

**Comment by kelunik** [comment]
I think the public API is fine now, but the encoding needs tests as it seems, decoding has tests.

**Comment by kelunik** [comment]
The README can be added later. ;-P
